# Generated by Django 5.2.6 on 2025-09-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('surname', models.CharField(max_length=20, verbose_name='surname')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('date_registered', models.DateField(verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('surname', models.CharField(max_length=20, verbose_name='surname')),
                ('position', models.CharField(max_length=50, verbose_name='position')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salary')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('date_hired', models.DateField(verbose_name='date hired')),
                ('is_active', models.BooleanField(default=False, verbose_name='True/False')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('name', models.CharField(max_length=200, verbose_name='project name')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('status', models.CharField(choices=[('planned', 'План'), ('in_progress', 'В процесі'), ('completed', 'Завершено')], default='planned')),
                ('date_created', models.DateField(verbose_name='date created')),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('clients', models.ManyToManyField(related_name='projects', to='main.client')),
                ('workers', models.ManyToManyField(related_name='projects', to='main.worker')),
            ],
        ),
    ]
