# Generated by Django 5.2.6 on 2025-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_registered',
            field=models.DateField(verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Ім’я'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(related_name='projects', to='main.client', verbose_name='Клієнти'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(verbose_name='Термін завершення'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Опис проекту'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва проекту'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'План'), ('in_progress', 'В процесі'), ('completed', 'Завершено')], default='planned', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(related_name='projects', to='main.worker', verbose_name='Співробітники'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_hired',
            field=models.DateField(verbose_name='Дата найму'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Ім’я'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Прізвище'),
        ),
    ]
